# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish to Registry

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v4
        with:
          path: this
      - name: Checkout Registry
        uses: actions/checkout@v4
        with:
          repository: snailbaron/registry
          path: registry
          token: ${{ secrets.token }}
      - name: Extract module name and version
        run: |
          pushd this
          deps=$(bazel mod deps)
          popd
          echo "bazel mod deps: '$deps'"

          deps="${deps#*\(}"
          deps="${deps%\)*}"

          module_name="${deps%@*}"
          module_version="${deps#*@}"

          this_remote=$(git -C this config remote.origin.url)
          this_last_commit=$(git -C this rev-parse origin/main)

          echo "current repository remote: $this_remote"
          echo "current repository commit: $this_last_commit"

          module_registry_dir="registry/modules/$module_name/$module_version"
          mkdir -p "$module_registry_dir"

          cp this/MODULE.bazel "$module_registry_dir/MODULE.bazel"
          cat > "$module_registry_dir/source.json" <<END
          {
              "type": "git_repository",
              "remote": "$this_remote",
              "commit": "$current_commit"
          }
          END

          git -C registry config user.name "snailbaron's bot"
          git -C registry config user.email "snailbaron@gmail.com"

          git -C registry add .
          git -C registry commit -m "Update $module_name:$module_version"
          git -C registry push
